import uuid
from django.db import models


class DataProcessing(models.Model):
    user_id = models.IntegerField()
    date_time = models.DateTimeField(null=True, blank=True)
    accepted_frame = models.FloatField(null=True, blank=True)
    accepted_frame_ratio = models.FloatField(null=True, blank=True)
    accepted_frame_spo2 = models.FloatField(null=True, blank=True)
    accepted_frame_spo2_ratio = models.FloatField(null=True, blank=True)
    accepted_frame_tdomain = models.FloatField(null=True, blank=True)
    accepted_frame_tdomain_ratio = models.FloatField(null=True, blank=True)
    activity_calories = models.FloatField(null=True, blank=True)
    activity_percentage = models.FloatField(null=True, blank=True)
    activity_step = models.FloatField(null=True, blank=True)
    # aws_request_id_data_sent = models.CharField(max_length=100, null=True, blank=True)
    # aws_request_id_metric = models.CharField(max_length=100, null=True, blank=True)
    # aws_request_id_upload = models.CharField(max_length=100, null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bucket = models.CharField(max_length=200, null=True, blank=True)
    dashboard_mode = models.CharField(max_length=20, null=True, blank=True)
    data_is_sent_to_client = models.BooleanField(null=True, blank=True)
    data_col_name = models.TextField(null=True, blank=True)
    datetime_gateway_sent = models.DateTimeField(null=True, blank=True)
    datetime_sensor = models.DateTimeField(null=True, blank=True)
    datetime_server_received = models.DateTimeField(null=True, blank=True)
    debug_data_length_too_short = models.JSONField(null=True, blank=True)
    debug_list_bpm_round = models.JSONField(null=True, blank=True)
    debug_list_status = models.JSONField(null=True, blank=True)
    error_sensor_onskin_status = models.CharField(max_length=255, null=True, blank=True)
    filename = models.TextField(null=True, blank=True)
    filepath = models.TextField(null=True, blank=True)
    hardware_mode = models.CharField(max_length=200, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    hr_fdomain = models.FloatField(null=True, blank=True)
    hr_fdomain_w_good_sqa = models.FloatField(null=True, blank=True)
    hr_tdomain = models.FloatField(null=True, blank=True)
    is_genmode_from_dashboard = models.BooleanField(null=True, blank=True)
    list_onskin_status_stdev_ratio = models.FloatField(null=True, blank=True)
    list_output_kurtosis = models.JSONField(null=True, blank=True)
    list_output_peakratio = models.JSONField(null=True, blank=True)
    list_output_skewness = models.JSONField(null=True, blank=True)
    list_output_stdev = models.JSONField(null=True, blank=True)
    list_phase_diff = models.JSONField(null=True, blank=True)
    list_sd_signal_w_sqa = models.JSONField(null=True, blank=True)
    list_sensor_onskin_status_ratio = models.FloatField(null=True, blank=True)
    median_list_output_kurtosis = models.FloatField(null=True, blank=True)
    median_list_output_peakratio = models.FloatField(null=True, blank=True)
    median_list_output_skewness = models.FloatField(null=True, blank=True)
    median_list_output_stdev = models.FloatField(null=True, blank=True)
    num_record_error = models.FloatField(null=True, blank=True)
    num_temperature_out_of_range = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_cv = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_mean = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_median = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_sd = models.FloatField(null=True, blank=True)
    packet_number = models.CharField(max_length=255, null=True, blank=True)
    point_awake = models.FloatField(null=True, blank=True)
    point_sleep = models.FloatField(null=True, blank=True)
    record_collected_by_sensor = models.CharField(max_length=255, null=True, blank=True)
    record_received_by_gateway = models.CharField(max_length=255, null=True, blank=True)
    record_server_received = models.CharField(max_length=255, null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_sd = models.FloatField(null=True, blank=True)
    rr_fdomain = models.FloatField(null=True, blank=True)
    rr_fdomain_w_good_sqa = models.FloatField(null=True, blank=True)
    rr_hybrid = models.FloatField(null=True, blank=True)
    rr_ibi = models.FloatField(null=True, blank=True)
    rr_sqaml = models.FloatField(null=True, blank=True)
    rr_sqaml_sd = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    rr_tdomain = models.FloatField(null=True, blank=True)
    sensor_contact_status = models.CharField(max_length=100, null=True, blank=True)
    sensor_id = models.CharField(max_length=255, null=True, blank=True)
    sensor_version = models.CharField(max_length=255, null=True, blank=True)
    sensor_onskin_status = models.FloatField(null=True, blank=True)
    sensor_onskin_status_stdev = models.FloatField(null=True, blank=True)
    signal_quality_status = models.CharField(max_length=100, null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    sleep_duration_seconds = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    sqa = models.FloatField(null=True, blank=True)
    sqa_index = models.FloatField(null=True, blank=True)
    total_frame = models.FloatField(null=True, blank=True)
    total_frame_spo2 = models.FloatField(null=True, blank=True)
    total_frame_tdomain = models.FloatField(null=True, blank=True)
    total_packet = models.FloatField(null=True, blank=True)
    val_sd_signal_w_sqa = models.FloatField(null=True, blank=True)
    val_sd_signal_wo_sqa = models.FloatField(null=True, blank=True)
    wavelets_transform = models.JSONField(null=True, blank=True)
    error_pipeline_calculation = models.FloatField(null=True, blank=True)
    hr_fdomain_w_good_sqa_sd = models.FloatField(null=True, blank=True)
    hr_sd = models.FloatField(null=True, blank=True)
    spo2_sd = models.FloatField(null=True, blank=True)
    wellness_calmness = models.FloatField(null=True, blank=True)
    wellness_stress = models.FloatField(null=True, blank=True)
    is_calculated = models.BooleanField(default=False)
    # bool_force_onskin_chest = models.BooleanField(
    #     null=True, blank=True, default=None
    # )  # TODO to be removed
    # bool_force_onskin_finger = models.BooleanField(
    #     null=True, blank=True, default=None
    # )  # TODO to be removed
    # bool_impute_rr = models.BooleanField(
    #     null=True, blank=True, default=None
    # )  # TODO to be removed
    # bool_impute_hr = models.BooleanField(
    #     null=True, blank=True, default=None
    # )  # TODO to be removed
    # bool_impute_spo2 = models.BooleanField(
    #     null=True, blank=True, default=None
    # )  # TODO to be removed
    display_label = models.CharField(max_length=250, null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    hr_chest = models.FloatField(null=True, blank=True)
    is_spo2_calc_error = models.BooleanField(null=True, blank=True)
    utc_offset = models.CharField(max_length=25, null=True, blank=True)
    resp_sp_version = models.CharField(max_length=25, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Data processing"

    def __str__(self):
        return f"{self.user_id}-{self.datetime_server_received}"

class MetricMinutesCache(models.Model):
    user_id = models.IntegerField()
    datetime_updated = models.DateTimeField(null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    battery_chest = models.FloatField(null=True, blank=True)
    battery_finger = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    flag = models.FloatField(null=True, blank=True)
    flag_notification = models.CharField(max_length=50, null=True, blank=True)
    dashboard_mode = models.CharField(max_length=20, null=True, blank=True)
    date_time = models.DateTimeField(null=True, blank=True)
    datetime_chest = models.DateTimeField(null=True, blank=True)
    datetime_finger = models.DateTimeField(null=True, blank=True)
    datetime_latest_valid_chest = models.DateTimeField(null=True, blank=True)
    datetime_latest_valid_finger = models.DateTimeField(null=True, blank=True)
    datetime_server_received = models.DateTimeField(null=True, blank=True)
    datetime_gateway_sent = models.DateTimeField(null=True, blank=True)
    hardware_mode = models.CharField(max_length=100, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    last_sync = models.DateTimeField(null=True, blank=True)
    last_sync_chest = models.DateTimeField(null=True, blank=True)
    last_sync_finger = models.DateTimeField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    sensor_id = models.CharField(max_length=255, null=True, blank=True)
    skin_contact = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_chest = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_finger = models.CharField(max_length=100, null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    news = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)

    datetime_manual_data_rr = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_body_temp = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_hr = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_weight = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_spo2 = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_blood_sugar = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_bp_dia = models.DateTimeField(null=True, blank=True)

    manual_data_rr = models.FloatField(null=True, blank=True)
    manual_data_blood_sugar = models.FloatField(null=True, blank=True)
    manual_data_body_temp = models.FloatField(null=True, blank=True)
    manual_data_weight = models.FloatField(null=True, blank=True)
    manual_data_bp_dia = models.FloatField(null=True, blank=True)
    manual_data_spo2 = models.FloatField(null=True, blank=True)
    manual_data_hr = models.FloatField(null=True, blank=True)
    manual_data_bp_sys = models.FloatField(null=True, blank=True)

    emr_rr = models.FloatField(null=True, blank=True)
    emr_blood_sugar = models.FloatField(null=True, blank=True)
    emr_body_temperature = models.FloatField(null=True, blank=True)
    emr_weight = models.FloatField(null=True, blank=True)
    emr_bp_dia = models.FloatField(null=True, blank=True)
    emr_spo2 = models.FloatField(null=True, blank=True)
    emr_hr = models.FloatField(null=True, blank=True)
    emr_bp_sys = models.FloatField(null=True, blank=True)

    datetime_emr_rr = models.DateTimeField(null=True, blank=True)
    datetime_emr_body_temperature = models.DateTimeField(null=True, blank=True)
    datetime_emr_hr = models.DateTimeField(null=True, blank=True)
    datetime_emr_weight = models.DateTimeField(null=True, blank=True)
    datetime_emr_spo2 = models.DateTimeField(null=True, blank=True)
    datetime_emr_blood_sugar = models.DateTimeField(null=True, blank=True)
    datetime_emr_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_emr_bp_dia = models.DateTimeField(null=True, blank=True)

    other_bp_sys = models.FloatField(null=True, blank=True)
    other_bp_dia = models.FloatField(null=True, blank=True)
    datetime_other_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_other_bp_dia = models.DateTimeField(null=True, blank=True)

    skin_contact_data = models.JSONField(null=True, blank=True)
    latest_skin_contact = models.JSONField(null=True, blank=True)
    data_sync = models.JSONField(null=True, blank=True)

    source = models.CharField(max_length=25, null=True, blank=True)

    utc_offset = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return f"{self.user_id}-{self.date_time}"

    class Meta:
        verbose_name_plural = "Metric minutes cache"

        
class MetricHourlyCache(models.Model):
    user_id = models.IntegerField()
    datetime_updated = models.DateTimeField(null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    battery_chest = models.FloatField(null=True, blank=True)
    battery_finger = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    datetime_latest_valid_chest = models.DateTimeField(null=True, blank=True)
    datetime_latest_valid_finger = models.DateTimeField(null=True, blank=True)
    flag = models.FloatField(null=True, blank=True)
    flag_notification = models.CharField(max_length=50, null=True, blank=True)
    dashboard_mode = models.CharField(max_length=20, null=True, blank=True)
    date_time = models.DateTimeField(null=True, blank=True)
    datetime_chest = models.DateTimeField(null=True, blank=True)
    datetime_finger = models.DateTimeField(null=True, blank=True)
    gateway_status = models.CharField(max_length=50, null=True, blank=True)
    datetime_server_received = models.DateTimeField(null=True, blank=True)
    datetime_gateway_sent = models.DateTimeField(null=True, blank=True)
    hardware_mode = models.CharField(max_length=100, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    last_connect_time = models.FloatField(null=True, blank=True)
    last_gateway_connect = models.DateTimeField(null=True, blank=True)
    last_sync = models.DateTimeField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    sensor_id = models.CharField(max_length=255, null=True, blank=True)
    sensor_chest_last_connect_time = models.DateTimeField(null=True, blank=True)
    sensor_finger_last_connect_time = models.DateTimeField(null=True, blank=True)
    sensor_status = models.CharField(max_length=50, null=True, blank=True)
    sensor_status_chest = models.CharField(max_length=50, null=True, blank=True)
    sensor_status_finger = models.CharField(max_length=50, null=True, blank=True)
    skin_contact = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_chest = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_finger = models.CharField(max_length=100, null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    news = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    has_manual_reading = models.BooleanField(null=True, blank=True)
    has_valid_other_reading = models.BooleanField(null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    body_temperature_SD = models.FloatField(null=True, blank=True)
    bp_dia_SD = models.FloatField(null=True, blank=True)
    bp_sys_SD = models.FloatField(null=True, blank=True)
    hr_SD = models.FloatField(null=True, blank=True)
    rr_SD = models.FloatField(null=True, blank=True)
    rr_dc_SD = models.FloatField(null=True, blank=True)
    rr_td_SD = models.FloatField(null=True, blank=True)
    skin_temperature_SD = models.FloatField(null=True, blank=True)
    spo2_SD = models.FloatField(null=True, blank=True)
    news_SD = models.FloatField(null=True, blank=True)
    weight_SD = models.FloatField(null=True, blank=True)
    blood_sugar_SD = models.FloatField(null=True, blank=True)
    activity_SD = models.FloatField(null=True, blank=True)
    listtime = models.DateTimeField(null=True, blank=True)
    datetime_local = models.DateTimeField(null=True, blank=True)
    listtimehr = models.DateTimeField(null=True, blank=True)
    recordDateHourGateway = models.FloatField(null=True, blank=True)
    recordDateHourServer = models.FloatField(null=True, blank=True)
    recordDateHourServerRR = models.FloatField(null=True, blank=True)
    recordDateHourServerHR = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs_finger = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs_chest = models.FloatField(null=True, blank=True)
    utc_offset = models.CharField(max_length=10, null=True, blank=True)
    def __str__(self):
        return f"{self.user_id}-{self.datetime_updated}"

    class Meta:
        verbose_name_plural = "Metric Hourly cache"

class SpotCache(models.Model):
    user_id = models.IntegerField()
    datetime_server_received = models.DateTimeField(null=True, blank=True)
    accepted_frame = models.FloatField(null=True, blank=True)
    accepted_frame_ratio = models.FloatField(null=True, blank=True)
    accepted_frame_spo2 = models.FloatField(null=True, blank=True)
    accepted_frame_spo2_ratio = models.FloatField(null=True, blank=True)
    accepted_frame_tdomain = models.FloatField(null=True, blank=True)
    accepted_frame_tdomain_ratio = models.FloatField(null=True, blank=True)
    activity_calories = models.FloatField(null=True, blank=True)
    activity_percentage = models.FloatField(null=True, blank=True)
    activity_step = models.FloatField(null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bucket = models.CharField(max_length=200, null=True, blank=True)
    dashboard_mode = models.CharField(max_length=20, null=True, blank=True)
    data_col_name = models.TextField(null=True, blank=True)
    date_time = models.DateTimeField(null=True, blank=True)
    datetime_gateway_sent = models.DateTimeField(null=True, blank=True)
    datetime_sensor = models.DateTimeField(null=True, blank=True)
    filename = models.TextField(null=True, blank=True)
    filepath = models.TextField(null=True, blank=True)
    hardware_mode = models.CharField(max_length=200, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    hr_fdomain = models.FloatField(null=True, blank=True)
    hr_fdomain_w_good_sqa = models.FloatField(null=True, blank=True)
    hr_tdomain = models.FloatField(null=True, blank=True)
    is_genmode_from_dashboard = models.BooleanField(null=True, blank=True)
    data_is_sent_to_client = models.BooleanField(null=True, blank=True)
    # aws_request_id_data_sent = models.CharField(max_length=100, null=True, blank=True)
    # aws_request_id_metric = models.CharField(max_length=100, null=True, blank=True)
    # aws_request_id_upload = models.CharField(max_length=100, null=True, blank=True)
    # latest_aws_request_id_upload = models.CharField(
    #     max_length=100, null=True, blank=True
    # )
    list_onskin_status_stdev_ratio = models.FloatField(null=True, blank=True)
    list_output_kurtosis = models.JSONField(null=True, blank=True)
    list_output_peakratio = models.JSONField(null=True, blank=True)
    list_output_skewness = models.JSONField(null=True, blank=True)
    list_output_stdev = models.JSONField(null=True, blank=True)
    list_phase_diff = models.JSONField(null=True, blank=True)
    list_sd_signal_w_sqa = models.JSONField(null=True, blank=True)
    debug_data_length_too_short = models.JSONField(null=True, blank=True)
    debug_list_bpm_round = models.JSONField(null=True, blank=True)
    debug_list_status = models.JSONField(null=True, blank=True)
    list_sensor_onskin_status_ratio = models.FloatField(null=True, blank=True)
    median_list_output_kurtosis = models.FloatField(null=True, blank=True)
    median_list_output_peakratio = models.FloatField(null=True, blank=True)
    median_list_output_skewness = models.FloatField(null=True, blank=True)
    median_list_output_stdev = models.FloatField(null=True, blank=True)
    num_record_error = models.FloatField(null=True, blank=True)
    num_temperature_out_of_range = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_cv = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_mean = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_median = models.FloatField(null=True, blank=True)
    onskin_2lightsources_median_diff_sd = models.FloatField(null=True, blank=True)
    packet_number = models.CharField(max_length=255, null=True, blank=True)
    point_awake = models.FloatField(null=True, blank=True)
    point_sleep = models.FloatField(null=True, blank=True)
    record_collected_by_sensor = models.CharField(max_length=255, null=True, blank=True)
    record_received_by_gateway = models.CharField(max_length=255, null=True, blank=True)
    record_server_received = models.CharField(max_length=255, null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_sd = models.FloatField(null=True, blank=True)
    rr_fdomain = models.FloatField(null=True, blank=True)
    rr_fdomain_w_good_sqa = models.FloatField(null=True, blank=True)
    rr_hybrid = models.FloatField(null=True, blank=True)
    rr_ibi = models.FloatField(null=True, blank=True)
    rr_sqaml = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    rr_tdomain = models.FloatField(null=True, blank=True)
    rr_sqaml_sd = models.FloatField(null=True, blank=True)
    sensor_contact_status = models.CharField(max_length=100, null=True, blank=True)
    sensor_id = models.CharField(max_length=255, null=True, blank=True)
    sensor_version = models.CharField(max_length=255, null=True, blank=True)
    sensor_onskin_status = models.FloatField(null=True, blank=True)
    sensor_onskin_status_stdev = models.FloatField(null=True, blank=True)
    signal_quality_status = models.CharField(max_length=100, null=True, blank=True)
    debug_rr_calulation_error = models.CharField(max_length=200, null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    sleep_duration_seconds = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    sqa = models.FloatField(null=True, blank=True)
    sqa_index = models.FloatField(null=True, blank=True)
    total_frame = models.FloatField(null=True, blank=True)
    total_frame_spo2 = models.FloatField(null=True, blank=True)
    total_frame_tdomain = models.FloatField(null=True, blank=True)
    total_packet = models.FloatField(null=True, blank=True)
    val_sd_signal_w_sqa = models.FloatField(null=True, blank=True)
    val_sd_signal_wo_sqa = models.FloatField(null=True, blank=True)
    wavelets_transform = models.JSONField(null=True, blank=True)
    error_pipeline_calculation = models.FloatField(null=True, blank=True)
    hr_fdomain_w_good_sqa_sd = models.FloatField(null=True, blank=True)
    hr_sd = models.FloatField(null=True, blank=True)
    spo2_sd = models.FloatField(null=True, blank=True)
    wellness_calmness = models.FloatField(null=True, blank=True)
    wellness_stress = models.FloatField(null=True, blank=True)
    error_sensor_onskin_status = models.CharField(max_length=255, null=True, blank=True)
    is_calculated = models.BooleanField(default=False)
    # bool_force_onskin_chest = models.BooleanField(null=True, blank=True, default=None)
    # bool_force_onskin_finger = models.BooleanField(null=True, blank=True, default=None)
    # bool_impute_rr = models.BooleanField(null=True, blank=True, default=None)
    # bool_impute_hr = models.BooleanField(null=True, blank=True, default=None)
    # bool_impute_spo2 = models.BooleanField(null=True, blank=True, default=None)
    display_label = models.CharField(max_length=250, null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    source = models.CharField(max_length=100, null=True, blank=True)
    hr_chest = models.FloatField(null=True, blank=True)
    is_spo2_calc_error = models.BooleanField(null=True, blank=True)

    utc_offset = models.CharField(max_length=10, null=True, blank=True)
    resp_sp_version = models.CharField(max_length=25, null=True, blank=True)

    def __str__(self):
        return f"{self.user_id}-{self.datetime_server_received}"

    class Meta:
        verbose_name_plural = "Spot cache"

class ApiDataSentOut(models.Model):
    user_id = models.IntegerField()
    datetime_server_received = models.DateTimeField()
    config = models.JSONField(null=True, blank=True)
    date_time = models.DateTimeField(null=True, blank=True)
    datetime_data_sent = models.DateTimeField(null=True, blank=True)
    lambda_request_id = models.CharField(max_length=100, null=True, blank=True)
    organization_setting = models.JSONField(null=True, blank=True)
    payload = models.JSONField(null=True, blank=True)
    response_status_code = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.user_id}-{self.datetime_server_received}"

    class Meta:
        verbose_name_plural = "Api data sent out"


class HealthData(models.Model):
    user_id = models.IntegerField()
    datetime = models.DateTimeField(null=True, blank=True)
    request_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    bp_sys = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    body_temp = models.FloatField(null=True, blank=True)
    datetime_received = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user_id} - {self.datetime}"

    class Meta:
        verbose_name_plural = "Health data"


class StagingHourlyCache(models.Model):
    user_id = models.IntegerField()
    datetime_updated = models.DateTimeField(null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    battery_chest = models.FloatField(null=True, blank=True)
    battery_finger = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    datetime_latest_valid_chest = models.DateTimeField(null=True, blank=True)
    datetime_latest_valid_finger = models.DateTimeField(null=True, blank=True)
    flag = models.FloatField(null=True, blank=True)
    flag_notification = models.CharField(max_length=50, null=True, blank=True)
    dashboard_mode = models.CharField(max_length=20, null=True, blank=True)
    date_time = models.DateTimeField(null=True, blank=True)
    datetime_chest = models.DateTimeField(null=True, blank=True)
    datetime_finger = models.DateTimeField(null=True, blank=True)
    gateway_status = models.CharField(max_length=50, null=True, blank=True)
    datetime_server_received = models.DateTimeField(null=True, blank=True)
    datetime_gateway_sent = models.DateTimeField(null=True, blank=True)
    hardware_mode = models.CharField(max_length=100, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    last_connect_time = models.FloatField(null=True, blank=True)
    last_gateway_connect = models.DateTimeField(null=True, blank=True)
    last_sync = models.DateTimeField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    sensor_id = models.CharField(max_length=255, null=True, blank=True)
    sensor_chest_last_connect_time = models.DateTimeField(null=True, blank=True)
    sensor_finger_last_connect_time = models.DateTimeField(null=True, blank=True)
    sensor_status = models.CharField(max_length=50, null=True, blank=True)
    sensor_status_chest = models.CharField(max_length=50, null=True, blank=True)
    sensor_status_finger = models.CharField(max_length=50, null=True, blank=True)
    skin_contact = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_chest = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_finger = models.CharField(max_length=100, null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    news = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    has_manual_reading = models.BooleanField(null=True, blank=True)
    has_valid_other_reading = models.BooleanField(null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    body_temperature_SD = models.FloatField(null=True, blank=True)
    bp_dia_SD = models.FloatField(null=True, blank=True)
    bp_sys_SD = models.FloatField(null=True, blank=True)
    hr_SD = models.FloatField(null=True, blank=True)
    rr_SD = models.FloatField(null=True, blank=True)
    rr_dc_SD = models.FloatField(null=True, blank=True)
    rr_td_SD = models.FloatField(null=True, blank=True)
    skin_temperature_SD = models.FloatField(null=True, blank=True)
    spo2_SD = models.FloatField(null=True, blank=True)
    news_SD = models.FloatField(null=True, blank=True)
    weight_SD = models.FloatField(null=True, blank=True)
    blood_sugar_SD = models.FloatField(null=True, blank=True)
    activity_SD = models.FloatField(null=True, blank=True)
    listtime = models.DateTimeField(null=True, blank=True)
    datetime_local = models.DateTimeField(null=True, blank=True)
    listtimehr = models.DateTimeField(null=True, blank=True)
    recordDateHourGateway = models.FloatField(null=True, blank=True)
    recordDateHourServer = models.FloatField(null=True, blank=True)
    recordDateHourServerRR = models.FloatField(null=True, blank=True)
    recordDateHourServerHR = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs_finger = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs_chest = models.FloatField(null=True, blank=True)
    utc_offset = models.CharField(max_length=10, null=True, blank=True)

class ProcessInProgress(models.Model):
    user_id = models.IntegerField()
    datetime = models.DateTimeField(auto_now_add=True)
    data_source = models.CharField(max_length=100)
    timestamp_hourly = models.DateTimeField(null=True, blank=True)
    timestamp_daily = models.DateTimeField(null=True, blank=True)
    utc_offset = models.CharField(max_length=100, null=True, blank=True)
    timestamp_server_received = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user_id}-{self.datetime}"

    class Meta:
        verbose_name_plural = "Process in Progress"
        ordering = ["-datetime"]


class MetricDailyCache(models.Model):
    user_id = models.IntegerField()
    datetime_updated = models.DateTimeField(null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    battery_chest = models.FloatField(null=True, blank=True)
    battery_finger = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    datetime_latest_valid_chest = models.DateTimeField(null=True, blank=True)
    datetime_latest_valid_finger = models.DateTimeField(null=True, blank=True)
    flag = models.FloatField(null=True, blank=True)
    flag_notification = models.CharField(max_length=50, null=True, blank=True)
    gateway_status = models.CharField(max_length=50, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    last_connect_time = models.FloatField(null=True, blank=True)
    last_gateway_connect = models.DateTimeField(null=True, blank=True)
    last_sync = models.DateTimeField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    sensor_chest_last_connect_time = models.DateTimeField(null=True, blank=True)
    sensor_finger_last_connect_time = models.DateTimeField(null=True, blank=True)
    sensor_status = models.CharField(max_length=50, null=True, blank=True)
    sensor_status_chest = models.CharField(max_length=50, null=True, blank=True)
    sensor_status_finger = models.CharField(max_length=50, null=True, blank=True)
    skin_contact = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_chest = models.CharField(max_length=100, null=True, blank=True)
    skin_contact_finger = models.CharField(max_length=100, null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    news = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    has_manual_reading = models.BooleanField(null=True, blank=True)
    has_valid_other_reading = models.BooleanField(null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    body_temperature_SD = models.FloatField(null=True, blank=True)
    bp_dia_SD = models.FloatField(null=True, blank=True)
    bp_sys_SD = models.FloatField(null=True, blank=True)
    hr_SD = models.FloatField(null=True, blank=True)
    rr_SD = models.FloatField(null=True, blank=True)
    rr_dc_SD = models.FloatField(null=True, blank=True)
    rr_td_SD = models.FloatField(null=True, blank=True)
    skin_temperature_SD = models.FloatField(null=True, blank=True)
    spo2_SD = models.FloatField(null=True, blank=True)
    news_SD = models.FloatField(null=True, blank=True)
    weight_SD = models.FloatField(null=True, blank=True)
    blood_sugar_SD = models.FloatField(null=True, blank=True)
    activity_SD = models.FloatField(null=True, blank=True)
    listdate = models.DateTimeField(null=True, blank=True)
    datetime_local = models.DateTimeField(null=True, blank=True)
    recordDateHourGateway = models.FloatField(null=True, blank=True)
    recordDateHourServer = models.FloatField(null=True, blank=True)
    recordDateHourServerRR = models.FloatField(null=True, blank=True)
    recordDateHourServerHR = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs_finger = models.FloatField(null=True, blank=True)
    recordReceivedByGateway_to_duration_hrs_chest = models.FloatField(null=True, blank=True)
    utc_offset = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self):
        return f"{self.user_id}-{self.datetime_updated}"

    class Meta:
        verbose_name_plural = "Metric Daily cache"


class Staging(models.Model):
    user_id = models.IntegerField()
    timestamp = models.DateTimeField(null=True, blank=True)
    patient_id = models.CharField(max_length=300, null=True, blank=True)
    sensor_name = models.CharField(max_length=100, null=True, blank=True)
    gateway_name = models.CharField(max_length=100, null=True, blank=True)
    sensor_battery = models.FloatField(null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    rr_dc = models.FloatField(null=True, blank=True)
    rr_td = models.FloatField(null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    finger_signal_quality = models.CharField(max_length=100, null=True, blank=True)
    chest_signal_quality = models.CharField(max_length=100, null=True, blank=True)
    finger_skin_contact = models.FloatField(null=True, blank=True)
    chest_skin_contact = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Staging"

    def __str__(self):
        return f"{self.user_id}-{self.timestamp}"


class OtherDeviceReading(models.Model):

    user_id = models.IntegerField(db_index=True)
    source = models.CharField(max_length=100, db_index=True)
    datetime = models.DateTimeField(db_index=True)
    blood_sugar = models.FloatField(null=True, blank=True)
    body_temperature = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    datetime_data_collected = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user_id}-{self.datetime}"

    class Meta:
        unique_together = ("user_id", "source", "datetime")
        verbose_name_plural = "Other Device Readings"
        ordering = ["-datetime"]


class PatientListCache(models.Model):
    user_id = models.IntegerField()
    resolution = models.CharField(max_length=50, null=True, blank=True)
    organization = models.CharField(max_length=500, null=True, blank=True)
    organization_resolution = models.CharField(max_length=500, null=True, blank=True)
    hr = models.FloatField(null=True, blank=True)
    rr = models.FloatField(null=True, blank=True)
    spo2 = models.FloatField(null=True, blank=True)
    bp_dia = models.FloatField(null=True, blank=True)
    bp_sys = models.FloatField(null=True, blank=True)
    activity = models.FloatField(null=True, blank=True)
    skin_temperature = models.FloatField(null=True, blank=True)
    news = models.FloatField(null=True, blank=True)
    datetime_hr = models.DateTimeField(null=True, blank=True)
    datetime_rr = models.DateTimeField(null=True, blank=True)
    datetime_spo2 = models.DateTimeField(null=True, blank=True)
    datetime_bp_dia = models.DateTimeField(null=True, blank=True)
    datetime_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_activity = models.DateTimeField(null=True, blank=True)
    datetime_skin_temperature = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_rr = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_body_temp = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_hr = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_weight = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_spo2 = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_blood_sugar = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_manual_data_bp_dia = models.DateTimeField(null=True, blank=True)
    manual_data_rr = models.FloatField(null=True, blank=True)
    manual_data_blood_sugar = models.FloatField(null=True, blank=True)
    manual_data_body_temp = models.FloatField(null=True, blank=True)
    manual_data_weight = models.FloatField(null=True, blank=True)
    manual_data_bp_dia = models.FloatField(null=True, blank=True)
    manual_data_spo2 = models.FloatField(null=True, blank=True)
    manual_data_hr = models.FloatField(null=True, blank=True)
    manual_data_bp_sys = models.FloatField(null=True, blank=True)
    emr_rr = models.FloatField(null=True, blank=True)
    emr_blood_sugar = models.FloatField(null=True, blank=True)
    emr_body_temperature = models.FloatField(null=True, blank=True)
    emr_weight = models.FloatField(null=True, blank=True)
    emr_bp_dia = models.FloatField(null=True, blank=True)
    emr_spo2 = models.FloatField(null=True, blank=True)
    emr_hr = models.FloatField(null=True, blank=True)
    emr_bp_sys = models.FloatField(null=True, blank=True)
    datetime_emr_rr = models.DateTimeField(null=True, blank=True)
    datetime_emr_body_temperature = models.DateTimeField(null=True, blank=True)
    datetime_emr_hr = models.DateTimeField(null=True, blank=True)
    datetime_emr_weight = models.DateTimeField(null=True, blank=True)
    datetime_emr_spo2 = models.DateTimeField(null=True, blank=True)
    datetime_emr_blood_sugar = models.DateTimeField(null=True, blank=True)
    datetime_emr_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_emr_bp_dia = models.DateTimeField(null=True, blank=True)
    other_bp_sys = models.FloatField(null=True, blank=True)
    other_bp_dia = models.FloatField(null=True, blank=True)
    datetime_other_bp_sys = models.DateTimeField(null=True, blank=True)
    datetime_other_bp_dia = models.DateTimeField(null=True, blank=True)
    skin_contact_data = models.JSONField(null=True, blank=True)
    data_sync = models.JSONField(null=True, blank=True)
    datetime_latest_valid_chest = models.DateTimeField(null=True, blank=True)
    datetime_latest_valid_finger = models.DateTimeField(null=True, blank=True)
    battery = models.FloatField(null=True, blank=True)
    battery_chest = models.FloatField(null=True, blank=True)
    battery_finger = models.FloatField(null=True, blank=True)
    display_label = models.CharField(max_length=250, null=True, blank=True)


class PatientDetail(models.Model):
    user_id = models.IntegerField()
    organization_id = models.CharField(max_length=500)
    resolution = models.CharField(max_length=50)